// Auto-generated by LibreLane
module mips_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  output[31:0] pc_out,
  output[31:0] instr_out,
  output[31:0] alu_result_out
);
endmodule
